### PR TITLE
feat(theme-color): toggle theme color along with dark mode

### PR DESCRIPTION
**Pull request by guygubaby**

### CODE REVIEW

**Comment by YunYouJun** [comment]
Thanks for your contribution. But I have a better idea.

Just use `useHead` to realize it. This will be more concise.

```ts
useHead({
  meta: [
    {
      name: `theme-color`,
      content: isDark ? 'xxx' : 'xxx',
    },
  ],
})
```

> https://github.com/vueuse/head

**Comment by guygubaby** [comment]
Oh my !!! Maybe i should dive deep into [vueuse/head](https://github.com/vueuse/head) doc 😂

**Comment by YunYouJun** [comment]
Do you want to resubmit it in a new PR with this way?

**Comment by guygubaby** [comment]
I've create a new one, maybe you can take a look if you have the time

**Pull request closed without merging**
